<?php
/**
 * Created by automatic generator
 * User: inhere
 * Date: 2018-05-27
 * Time: 12:16
 * Template: res/templates/routes.stub
 *
 * @notice Please don't edit this file, it is auto-generated.
 * @var \Inhere\Route\ORouter $router
 */

$router->get('/', \App\Http\Controller\HomeController::class);

// The following information is automatically generated by the command `route:build`

/** @see \App\Http\Controller\ErrorController */
$router->map(['GET'], '/error', 'App\Http\Controller\ErrorController@index');
$router->map(['GET'], '/500', 'App\Http\Controller\ErrorController@error');
$router->map(['GET'], '/404', 'App\Http\Controller\ErrorController@notFound');
$router->map(['GET'], '/405', 'App\Http\Controller\ErrorController@notAllowed');

/** @see \App\Http\Controller\HomeController */
$router->map(['GET'], '/', 'App\Http\Controller\HomeController@index');
$router->map(['GET'], '/home/log', 'App\Http\Controller\HomeController@log');
$router->map(['GET'], '/home/routes', 'App\Http\Controller\HomeController@routes');
$router->map(['GET'], '/home/test', 'App\Http\Controller\HomeController@test');
$router->map(['GET'], '/home/config', 'App\Http\Controller\HomeController@config');
$router->map(['GET'], '/home/json', 'App\Http\Controller\HomeController@json');

/** @see \App\Http\Controller\RestController */
$router->map(['GET'], '/rest', 'App\Http\Controller\RestController@index');

